package ru.strbnm.store.testcases;

import java.math.BigDecimal;
import java.util.stream.Stream;

public class ProductTestCase {
    public record TestCase(
            int page,
            int size,
            String text,
            BigDecimal price_from,
            BigDecimal price_to,
            String letter,
            String sorting,
            int countOnPage,
            String firstProductName,
            BigDecimal firstProductPrice,
            String lastProductName,
            BigDecimal lastProductPrice) {}

    public static Stream<TestCase> provideTestCases() {
        return Stream.of(
                new TestCase(
                        0,
                        5,
                        null,
                        null,
                        null,
                        null,
                        null,
                        5,
                        "Eco Gadget 690",
                        new BigDecimal("464.64"),
                        "Super Item 561",
                        new BigDecimal("432.91")),
                new TestCase(
                        1,
                        5,
                        null,
                        null,
                        null,
                        null,
                        null,
                        5,
                        "Ultra Gadget 123",
                        new BigDecimal("191.38"),
                        "Ultra Widget 734",
                        new BigDecimal("84.71")),
                new TestCase(
                        0,
                        5,
                        null,
                        null,
                        null,
                        null,
                        "NAME_ASC",
                        5,
                        "Eco Gadget 690",
                        new BigDecimal("464.64"),
                        "Super Item 561",
                        new BigDecimal("432.91")),
                new TestCase(
                        0,
                        5,
                        null,
                        null,
                        null,
                        null,
                        "NAME_DESC",
                        5,
                        "Ultra Widget 734",
                        new BigDecimal("84.71"),
                        "Ultra Gadget 123",
                        new BigDecimal("191.38")),
                new TestCase(
                        0,
                        10,
                        null,
                        null,
                        null,
                        null,
                        "PRICE_ASC",
                        10,
                        "Ultra Object 450",
                        new BigDecimal("31.17"),
                        "Eco Gadget 690",
                        new BigDecimal("464.64")),
                new TestCase(
                        0,
                        10,
                        null,
                        null,
                        null,
                        null,
                        "PRICE_DESC",
                        10,
                        "Eco Gadget 690",
                        new BigDecimal("464.64"),
                        "Ultra Object 450",
                        new BigDecimal("31.17")),
                new TestCase(
                        0,
                        5,
                        "Object",
                        null,
                        null,
                        null,
                        "NAME_ASC",
                        3,
                        "Smart Object 598",
                        new BigDecimal("357.76"),
                        "Ultra Object 457",
                        new BigDecimal("334.53")),
                new TestCase(
                        0,
                        5,
                        "Object",
                        null,
                        null,
                        null,
                        "NAME_DESC",
                        3,
                        "Ultra Object 457",
                        new BigDecimal("334.53"),
                        "Smart Object 598",
                        new BigDecimal("357.76")),
                new TestCase(
                        0,
                        10,
                        "Object",
                        null,
                        null,
                        null,
                        "PRICE_ASC",
                        3,
                        "Ultra Object 450",
                        new BigDecimal("31.17"),
                        "Smart Object 598",
                        new BigDecimal("357.76")),
                new TestCase(
                        0,
                        10,
                        "Object",
                        null,
                        null,
                        null,
                        "PRICE_DESC",
                        3,
                        "Smart Object 598",
                        new BigDecimal("357.76"),
                        "Ultra Object 450",
                        new BigDecimal("31.17")),
                new TestCase(
                        0,
                        5,
                        null,
                        new BigDecimal("100"),
                        new BigDecimal("300"),
                        null,
                        "NAME_ASC",
                        3,
                        "Eco Thing 576",
                        new BigDecimal("211.65"),
                        "Ultra Item 402",
                        new BigDecimal("289.61")),
                new TestCase(
                        0,
                        5,
                        null,
                        new BigDecimal("100"),
                        new BigDecimal("300"),
                        null,
                        "NAME_DESC",
                        3,
                        "Ultra Item 402",
                        new BigDecimal("289.61"),
                        "Eco Thing 576",
                        new BigDecimal("211.65")),
                new TestCase(
                        0,
                        10,
                        null,
                        new BigDecimal("200"),
                        new BigDecimal("400"),
                        null,
                        "PRICE_ASC",
                        5,
                        "Eco Thing 576",
                        new BigDecimal("211.65"),
                        "Smart Object 598",
                        new BigDecimal("357.76")),
                new TestCase(
                        0,
                        10,
                        null,
                        new BigDecimal("200"),
                        new BigDecimal("400"),
                        null,
                        "PRICE_DESC",
                        5,
                        "Smart Object 598",
                        new BigDecimal("357.76"),
                        "Eco Thing 576",
                        new BigDecimal("211.65")),
                new TestCase(
                        0,
                        5,
                        "Eco",
                        new BigDecimal("100"),
                        new BigDecimal("300"),
                        null,
                        "NAME_ASC",
                        1,
                        "Eco Thing 576",
                        new BigDecimal("211.65"),
                        "Eco Thing 576",
                        new BigDecimal("211.65")),
                new TestCase(
                        0,
                        5,
                        "Gadget",
                        new BigDecimal("100"),
                        new BigDecimal("300"),
                        null,
                        "NAME_DESC",
                        1,
                        "Ultra Gadget 123",
                        new BigDecimal("191.38"),
                        "Ultra Gadget 123",
                        new BigDecimal("191.38")),
                new TestCase(
                        0,
                        10,
                        "Ultra",
                        new BigDecimal("200"),
                        new BigDecimal("400"),
                        null,
                        "PRICE_ASC",
                        2,
                        "Ultra Item 402",
                        new BigDecimal("289.61"),
                        "Ultra Object 457",
                        new BigDecimal("334.53")),
                new TestCase(
                        0,
                        10,
                        "Ultra",
                        new BigDecimal("200"),
                        new BigDecimal("400"),
                        null,
                        "PRICE_DESC",
                        2,
                        "Ultra Object 457",
                        new BigDecimal("334.53"),
                        "Ultra Item 402",
                        new BigDecimal("289.61")),
                new TestCase(
                        0,
                        5,
                        null,
                        null,
                        null,
                        "U",
                        "NAME_ASC",
                        5,
                        "Ultra Gadget 123",
                        new BigDecimal("191.38"),
                        "Ultra Widget 734",
                        new BigDecimal("84.71")),
                new TestCase(
                        0,
                        5,
                        null,
                        null,
                        null,
                        "E",
                        "NAME_DESC",
                        3,
                        "Eco Thing 576",
                        new BigDecimal("211.65"),
                        "Eco Gadget 690",
                        new BigDecimal("464.64")),
                new TestCase(
                        0,
                        10,
                        null,
                        null,
                        null,
                        "S",
                        "PRICE_ASC",
                        2,
                        "Smart Object 598",
                        new BigDecimal("357.76"),
                        "Super Item 561",
                        new BigDecimal("432.91")),
                new TestCase(
                        0,
                        10,
                        null,
                        null,
                        null,
                        "S",
                        "PRICE_DESC",
                        2,
                        "Super Item 561",
                        new BigDecimal("432.91"),
                        "Smart Object 598",
                        new BigDecimal("357.76")));
    }
}
